spring.application.name=HortaHub

spring.datasource.url=jdbc:postgresql://localhost:5432/hortadata
spring.datasource.username=user
spring.datasource.password=""

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Cria as base de forma automatica
# CUIDADO | Usando [crate-drop] ele cria na execucao e destroi quando encerra o programa
spring.jpa.hibernate.ddl-auto=create

# Mostra o SQL que o Spring está executando no console
spring.jpa.properties.hibernate.format_sql=true