spring.application.name=HortaHub

spring.datasource.url=jdbc:postgresql://localhost:5432/hortadata
spring.datasource.username=postgres
spring.datasource.password=winsucks

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true
